# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc1bc5843a64e4a621663d6b9a7b49c8ecf86d99f0031b8473c7d39f25d8630e67225079359048937db7d228cf61c3c7b186058baa36f6b4658d546654334a64

test:
  secret_key_base: 4464af8acd00ef81f7b35621c58dc1751a0ec2b89eed38adb37646582c9176eb050ab64414cde4aa994ffde01f5059b4c70985e8d01af8334b871781c907e6be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
